'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Berandaadmin
    
    '''<summary>
    '''beranda_Murid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beranda_Murid As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''beranda_materi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beranda_materi As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''beranda_css control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beranda_css As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''beranda_html control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beranda_html As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''beranda_konfirmasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beranda_konfirmasi As Global.System.Web.UI.WebControls.HyperLink
End Class
