'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index
    
    '''<summary>
    '''form_login_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form_login_admin As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''username_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents username_admin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''requ_username_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requ_username_admin As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''password_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password_admin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''requ_password_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requ_password_admin As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btn_login_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_login_admin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''peringatan_login_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents peringatan_login_admin As Global.System.Web.UI.WebControls.Label
End Class
